### PR TITLE
Fix widgets for showing info on cloud image builds.

### PR DESCRIPTION
**Pull request by rtnpro**
Improve widgets for displaying info on cloud image: upload and test builds.

### CODE REVIEW

**Comment by ralphbean** [comment]
Looks like this:

cloud-upload

**Comment by ralphbean** [comment]
Some thoughts:

- I think we used to have links to the original koji builds of the images so people could download them directly and mess with them.  QA team people used this to test the images on different platforms.
- For the new AMI entries, can you add links to the AMIs in amazon's web interface?  A link like this would do it:  ``https://redirect.fedoraproject.org/console.aws.amazon.com/ec2/v2/home?region=us-east-1#LaunchInstanceWizard:ami=ami-acd999c4``
- I notice that the AMI ids for the uploads and the AMI ids for the tests do not match (nor do the regions).  Should there be an entry for each region?  I think we support about 9 of them.  See https://getfedora.org/en/cloud/download/ for an example.

**Comment by rtnpro** [comment]
@ralphbean Let's discuss today on IRC with @oddshocks to finalize the implementation of this widget.

**Comment by oddshocks** [comment]
@ralphbean, since the image is tested in one region before it's copied to all the others, and not tested post-copy, there will only be 1 test message per batch of uploads.

The structure of the fedmsgs I set up here is probably not the greatest. As it stands now, if the test fails, then the whole upload will fail. So it's not really important to know if the test passes or not, because the whole image.upload will be "failed" if the related test fails. In short, a failed test means a failed upload. I suggest we skip the "(Test)" section and just have "Cloud Images", at least for now.

Other than that, I think it looks good. Once I get a newer version of Fedimg out, the fedmsgs will have more info in them, like virtualization type, and volume type. When that happens, someone or myself can add those parts to the widget. As it stands now, because of how I structured the fedmsgs, some uploads will appear to be the same in releng dash. Only after looking at the AMI in EC2 will people be able to tell if it's HVM/PV, standard/gp2, whatever. But -- this looks good in my opinion, and is also the best that can be done with the current fedmsgs. :)

**Comment by rtnpro** [comment]
@oddshocks I will remove the section for ``Cloud Images (Test)`` for now. Also, I will add link to the AMI.

**Comment by ralphbean** [comment]
@rtnpro I think we do need to get the links to the original koji builds back, if possible.  It might necessitate splitting it out into more sections or columns.  I.e., one for "cloud images" (built in koji) and another for "uploaded AMIs" (uploaded to amazon, etc..).

releng just asked if we could include not just the images we already had, but also the docker base image and the new vagrant images.

**Comment by ralphbean** [comment]
:+1: from me here.  @oddshocks, do you have any further feedback?

**Comment by ralphbean** [comment]
Thanks for working on this @rtnpro!

**Comment by oddshocks** [comment]
No, good from me here. Thanks to the both of you for helping start up this section, which will be immensely useful to the cloud team, especially as it evolves.

**Pull request merged**
